### PR TITLE
chore(tests): rename support dir

### PR DESCRIPTION
**Pull request by fatgeekuk**

### CODE REVIEW

**Comment by ljkbennett** [comment]
Personally I think I'd prefer not to do this as I believe this folder was generated by the phoenix generator and it may be that other generators for installing other dependencies may rely on it existing or create additional support folders, but I don't feel _too_ strongly about it either way.

**Comment by fatgeekuk** [comment]
I've checked through the phoenix codebase and the only mentions in any generators of 'support' is the one that generates the new phoenix project.

All other mentions are referencing the support folder within the phoenix tests themselves rather than referencing the support directory within a target project.

**Comment by ljkbennett** [comment]
Yes, but, as I said, if "other dependencies" have generators they may rely on it existing. I'd just rather stick with the phoenix pattern rather than making arbitrary changes, but if everyone else is happy, go ahead.

**Comment by OCannings** [comment]
I can see the reasoning behind this change, but I'm also reluctant to move away from the default project structure.

**Pull request closed without merging**
